### ISSUE TITLE
Broken CDN worker for repo.anaconda.com

### ISSUE THREAD

**Issue by kalebo** [conda/infrastructure#1073]
### Checklist

- [x] I added a descriptive title
- [x] I searched open reports and couldn't find a duplicate

### What happened?

One of the cloudflare CDN workers for repo.anaconda.com seems to be broken for the Salt Lake City region. It returns 500 error codes for GET requests both within conda, as well via `curl` or a browser. It has been doing this for about 4 hours at this point.

Specifically, the error output is:
```
CondaHTTPError: HTTP 500 INTERNAL SERVER ERROR for url <https://repo.anaconda.com/pkgs/main/linux-64/repodata.json>
Elapsed: 00:06.508551
CF-RAY: 8ece52c17e992c69-SLC
```

**Comment by chenghlee** [comment]
Checked with Anaconda's infrastructure team: we identified a spike in HTTP 500 errors affecting ~1% of CDN traffic for repo.anaconda.com, starting around 2024-12-04 1600 UTC. The problem appears to be isolated to certain regions (so far: Detroit, Malaysia, and possibly Utah), and the issue seems to be on our CDN provider's side (CloudFlare). We've opened a ticket with them and will update the community as we get more information.

**Comment by jezdez** [comment]
We've opened an incident and published it on Anaconda's status page: https://anaconda.statuspage.io/incidents/qfv2n662hyym

**Comment by jezdez** [comment]
It seems like the issue was found by the infrastructure provider and a fix is rolling out at the moment

**Comment by jezdez** [comment]
Closing as completed following confirmation by Anaconda on https://anaconda.statuspage.io/incidents/qfv2n662hyym

**Comment by jakirkham** [comment]
Thank you both! 🙏
