### ISSUE TITLE
Add `upstream` and `downstream` labels

### ISSUE THREAD

**Issue by jaimergp** [conda/infrastructure#698]
### What is the idea?

Have a label to mark issues or PRs as something that needs to be tackled by doing work in an upstream dependency.

### Why is this needed?

Some issues at conda-libmamba-solver are not about our integration layer, but something that we need to do in `libmamba` itself or `libsolv`.

### What should happen?

Add the following labels initially:

- `upstream`
- `downstream`
- `downstream::anaconda`
- `downstream::conda-forge`

### Additional Context

~I am not sure which `prefix::` it should go in 😬 ~

**Comment by kenodegard** [comment]
Could also add complimentary `downstream` labels:

- `downstream::anaconda` - indicates that the issue impacts Anaconda's packaging teams
- `downstream::conda-forge` - indicates that the issue impacts conda-forge
- `downstream::conda-libmamba-solver` - indicates that the issue impacts `conda-libmamba-solver`
- `downstream` - some downstream project or team is impacted

**Comment by dkomisar** [comment]
The packaging team definitely wants a way to note which issues impact them, so this would be great.

**Comment by kalawac** [comment]
@kenodegard re: the question of what prefix these should go in, could `Modifiers` work?

**Comment by kenodegard** [comment]
@kalawac Ah, I see now that we've been using inconsistent terminology here, sorry for the confusion. Clarifying with terminology used in [`HWUG.md`](https://github.com/conda/infrastructure/blob/main/HOW_WE_USE_GITHUB.md#how-are-new-labels-defined).

We want to define two new high-level category labels, upstream and downstream (I've provided some simple descriptions here, feel free to wordsmith further):

- `upstream`: this issue/PR is caused by an upstream dependency
- `downstream`: this issue/PR is impacting a downstream dependency

We also want to offer two additional sub-categories/topics for the downstream label:

- `downstream::anaconda`: this issue/PR is impacting Anaconda's packaging teams
- `downstream::conda-forge`: this issue/PR is impacting the conda-forge community

All of these new labels are new types, so we should pick a neutral, unused color for these labels and group them under a new header in `global.yml`. This header isn't too important as it's purely a comment within `global.yml` and just helps us keep things organized. I proposed elsewhere to call it "Upstream & Downstream" and Jannis proposed to call them "Relations", either work, so feel free to take your pick.
